{
 "title": "audio",
 "time": { "from": "2024-09-17T20:31:05.598Z", "to": "2024-09-17T20:32:38.038Z" },
 "panels": [
  {
   "title": "PulseRate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Pulseoxy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"pulseoxy_samples\" and\r\n    r._field == \"PulseRate\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean_PulseRate\")\r\n  "
    }
   ]
  },
  {
   "title": "spO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Pulseoxy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"pulseoxy_samples\" and\r\n    r._field == \"spO2\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean_spO2\")\r\n"
    }
   ]
  },
  {
   "title": "Respiration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"Respiratory\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"resp_belt_samples\" and\r\n    r._field == \"resp_value\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean_respiration\")"
    }
   ]
  },
  {
   "title": "ECG",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"ECG\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"ecg_samples\" and\r\n    r._field == \"ecg_value\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean_ECG\")"
    }
   ]
  },
  {
   "title": "Pulse Wave",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"Pulseoxy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"pulseoxy_samples\" and\r\n    r._field == \"PulseWave\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean_PulseWave\")"
    }
   ]
  },
  {
   "title": "snoring events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"audio\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"snoring_events\" and\r\n    r._field == \"probability\"\r\n  )\r\n"
    }
   ]
  }
 ]
}